services:
  backend:
    build: ./backend
    container_name: projectflow-backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend/database:/app/database

  frontend:
    build: ./frontend
    container_name: projectflow-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
